version: "3"

services:
    rubban:
        image: sherifabdlnaby/rubban:latest
        environment:
            RUBBAN_KIBANA_HOST: "kibana:5601"
            RUBBAN_KIBANA_USER: "elastic"
            RUBBAN_KIBANA_PASSWORD: "changeme"
            RUBBAN_AUTOINDEXPATTERN_ENABLED: 'true'
            RUBBAN_AUTOINDEXPATTERN_SCHEDULE: '*/5 * * * *'
            RUBBAN_AUTOINDEXPATTERN_GENERALPATTERNS: '[{"pattern":"logs-apache-access-*-?","timeFieldName":"@timestamp"}]'
