on: [push, pull_request]
name: Build
jobs:
    build:
        strategy:
            matrix:
                go-version: [1.13.x]
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: Install Go
              uses: actions/setup-go@v1
              with:
                  go-version: ${{ matrix.go-version }}
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Build
              run: make build && make build-alpine
            - name: Test
              run: go test ./...
