on: [push, pull_request]
name: GolangCI-Lint
jobs:
    golang-ci-lint:
        name: Lint project using GolangCI Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code into the Go module directory
                uses: actions/checkout@v1

            -   name: GolangCI-Lint Action
                uses: matoous/golangci-lint-action@v1.23.3
                with:
                    config: .golangci.yml
